version: '3.4'

services:
  app:
    build: 
      context: ./
      dockerfile: ./build/Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules
    ports:
      - 3000:3000
      - 9229:9229
