version: "3"

services:
  app:
    build: 
      context: ./
      dockerfile: ./build/Dockerfile.prod
    environment:
      MONGO_URL: "mongodb://db:27017/test"
      NODE_ENV: production
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mongo
    volumes: 
      - mongo_database:/data/db

volumes:
  mongo_database: